services:
  web:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"     # Для HTTPS через TCP (HTTP/1.1 и HTTP/2)
      - "443:443/udp" # Для HTTP/3 через UDP
    volumes:
      - ./nginx:/usr/share/nginx
